name: "cmake-format lint"
author: "Genci Berisha (neg-c)"
description: "Github Action that check if code is formatted correctly using cmake-format"

branding:
  icon: "align-left"
  color: "orange"
inputs:
  source:
    description: "Source file/folder to check formatting or directoryPath"
    required: false
    default: "."
  exclude:
    description: "Folders to exclude from formatting check"
    required: false
    default: "none"
  config:
    description: "Use .cmake-format style"
    required: false
    default: False
  inplace:
    description: "Just fix files (`cmake-format -i`) instead of returning a diff"
    required: false
    default: False
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --inplace
    - ${{ inputs.inplace }}
    - --config
    - ${{ inputs.config }}
    - --exclude
    - ${{ inputs.exclude }}
    - --color
    - always
    - ${{ inputs.source }}
