name: "cmake-format lint"
author: "Genci Berisha (neg-c)"
description: "Github Action that check if code is formatted correctly using cmake-format"

branding:
  icon: "align-left"
  color: "orange"
inputs:
  source:
    description: "Source folder to check formatting or directoryPath"
    required: false
    default: "."
  exclude:
    description: "Folder to exclude from formatting check"
    required: false
    default: "none"
  config:
    description: "Formatting style to use"
    required: false
    default: ".cmake-format"
  inplace:
    description: "Just fix files (`cmake-format -i`) instead of returning a diff"
    required: false
    default: False
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
